### ISSUE TITLE
multithread support

### ISSUE THREAD

**Issue by jianshu93** [fmedina7/ClonOr_cpp#3]
Dear team, 

I saw that the openmp library was used/linked for multithread support, but I cannot see an option to use multiple threads. N =0 or 1, I see no difference. 

Thanks,

Jianshu

**Comment by fjmedinaaguayo** [comment]
Hi Jianshu,

Thanks for reaching out! Just as you mentioned, running the code with N=0 or with N=1 provides no difference, there is a note about this in the readme.

If you want to use multiple threads you need to choose N>1, e.g. N=2 will run using 2 threads. A good idea would be to se N equal to the number of cores available in your machine o cluster.

Regards,
Felipe

**Comment by jianshu93** [comment]
Thanks!this is clear. Multithreaded run will be much faster right.
